-- 코드를 입력하세요


-- 2022년 1월에 BOOK_ID 를 기준으로 SUM 

SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum((SALES * PRICE)) as TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) as sales
      FROM BOOK_SALES 
      WHERE to_char(SALES_DATE, 'YYYYMM') = '202201'
      GROUP BY BOOK_ID) bs
LEFT JOIN BOOK b ON bs.BOOK_ID = b.BOOK_ID
RIGHT JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
GROUP BY a.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY a.AUTHOR_ID, CATEGORY DESC;



