-- 코드를 입력하세요
SELECT ri.REST_ID, 
       REST_NAME, 
       FOOD_TYPE, 
       FAVORITES, 
       ADDRESS,
       SCORE
FROM REST_INFO ri 
right JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
           FROM REST_REVIEW
           GROUP BY REST_ID) rr 
ON ri.REST_ID = rr.REST_ID
WHERE ADDRESS like '서울'||'%'
ORDER BY SCORE DESC, FAVORITES DESC;