-- 코드를 입력하세요
SELECT ('/home/grep/src/' || ub.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD ub 
LEFT JOIN USED_GOODS_FILE f 
ON ub.BOARD_ID = f.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC; 